### ISSUE TITLE
update to Mini-XML?

### ISSUE THREAD

**Issue by Dogora** [tjko/nxgipd#1]
nxgipd works with Mini-XML v2.6, but not the current version 2.8. It compiles fine. But, it fails to search the tree properly, so always gives an error that it cannot find the serial device in configuration. The error seems to be around line 50 of configuration.c, though I could be wrong.

**Comment by tjko** [comment]
Can you try with Mini-XML v2.9, if you still see the issued?   I just tested with v2.9 and it seemed to work just fine...

**Comment by Dogora** [comment]
Hmmm... I had a bit of time to look at the mxml code and didn't see why 2.9 would not work, given the changes from 2.6. I'll try again on my laptop computer. It's entirely possible I did something wrong. openSUSE 13.1 uses 2.6, and maybe I messed up my upgrade.

**Comment by Dogora** [comment]
I just checked, and nxgipd 0.9.1 works fine with Mini-XML 2.9. I didn't re-check 2.8, though.
