### ISSUE TITLE
NX16 Compatibility 

### ISSUE THREAD

**Issue by chrisk-81** [tjko/nxgipd#10]
Hi,

Do you think this software would be compatible with the Reliance128/NX16 here in Australia?

This is a Caddx/Networx panel and is compatible with the NX584E.

**Comment by tjko** [comment]
It should work fine.   But you may have to initially configure, in _ngxipd.conf_, maximum zones/partitions as auto detection might not work.

Just let me know what panel ID nxgipd reports for this panel (and what are the maximum zones/partitions this panel supports) and I can add this panel in the known panels table, so future versions of nxgipd will automatically detect this panel.

**Comment by draget** [comment]
My Australian NX-4 is reported as NX-8 (maxzones=48, maxpartitions=8) with panelID = 3.

**Comment by tjko** [comment]
@draget, thanks. I added entry for panel id 3.
