### ISSUE TITLE
Feature request: 2 new nxcmd commands to set the clock and save the status XML file

### ISSUE THREAD

**Issue by Dogora** [tjko/nxgipd#4]
I have a suggestion for 2 more commands to the daemon via nxcmd: one to set the panel's clock, and one to save the status XML file. While these commands may not get used much, they could be nice to have at times.

**Comment by kirkawolff** [comment]
Seconded

**Comment by tjko** [comment]
I added "setclock" option/command to _nxcmd_: a75b7bf845e051a499e4839d46bbc7a30f12931e

_nxcmd_ is for "issuing" command to the alarm panel, so issuing commands to the daemon/server process should be separate mechanism.  For now daemon process saves the status file every time it receives SIGUSR1 signal: 81974ec1fa39cd73c873202c0d23053691440c2e

But status file saving probably should happen periodically, to guard against power loss, etc. maybe it really should be configurable option to specify how often daemon should save its status...

**Comment by Dogora** [comment]
Thanks for the addition.
